import Nav from "@/components/Nav";
import { MoriartyIcon } from "@/components/icons";

export default function MoriartyPage() {
  return (
    <div className="flex flex-1 flex-col bg-ink-gradient">
      <Nav />
      <main className="mx-auto w-full max-w-5xl px-8 py-16 sm:px-16 sm:py-24">
        <MoriartyIcon className="h-12 w-12 text-brass" />
        <h1 className="mt-4 font-serif text-4xl leading-tight text-parchment sm:text-5xl">
          Moriarty
        </h1>

        <div className="mt-16 flex flex-col gap-16">
          <section className="max-w-prose">
            <h2 className="font-serif text-2xl text-parchment">
              What it does
            </h2>
            <p className="mt-4 text-base leading-relaxed text-parchment/90">
              Moriarty gives business and monetization advice: the mind
              behind the scheme, turned toward strategy instead of crime.
            </p>
          </section>

          <section className="max-w-prose">
            <h2 className="font-serif text-2xl text-parchment">
              How it works
            </h2>
            <p className="mt-4 text-base leading-relaxed text-parchment/90">
              Moriarty runs on the same decisive, single-answer, no-hedging
              schema as Sherlock, specialized for monetization and business
              strategy questions. A fixed disclaimer is appended to every
              response server-side, never generated by the model, so the
              persona&apos;s voice stays confident while the liability
              framing stays consistent.
            </p>
          </section>
        </div>

        <p className="mt-16 max-w-prose text-xs leading-relaxed text-sage">
          Moriarty never gives securities, investment, or trading advice. All
          output is general business commentary, not professional financial
          or legal advice.
        </p>
      </main>
    </div>
  );
}
